import React from "react";
import Link from "next/link";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

import NavBar from "@/components/NavBar";
import SocialMedia from "@/components/SocialMedia";
import HomeIcons from "@/components/HomeIcons";
import SubNavBar from "@/components/SubNavBar";
import ProfileInfo from "@/components/ProfileInfo";
import Footer from "@/components/Footer";
import BookingBtn from "@/components/BookingBtn";
import { useState } from "react";

const Home = () => {

  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Caleb Mission UK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-milena-logo.png" />
      </Head>

      <main className="bg-rgb-yellow-caleb">
        <section className="flex flex-col h-screen">
          <NavBar />

          {/* <SubNavBar /> */}

          {/* This is the SubNavBar */}
          <div className="flex justify-center items-center h-4/5">
            <Link href="/">
              {/* 
              <h1 className="text-xl rgb-blue-caleb">Caleb Mission UK</h1>
              */}
              <ProfileInfo />

            </Link>
            
          </div>
          <SocialMedia />


        </section>

        <Footer darkMode={darkMode}/>
      </main>
    </div>
  );
};

export default Home;
